In [16]:
import numpy as np

In [17]:
X = np.array([[1],[2],[3],[4],[5],[6],[7],[8]])
y = np.array([25000,30000,35000,40000,45000,50000,55000,60000])

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train,X_test,y_train,y_test = train_test_split(
   X,y,test_size = 0.2,random_state = 42 
)

In [22]:
from sklearn.linear_model import Ridge

In [23]:
#create model

In [66]:
model = Ridge(alpha = 100)

In [67]:
#train model

In [68]:
model.fit(X_train,y_train);

In [69]:
#prediction

In [70]:
y_pred = model.predict(X_test)

In [71]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [72]:
print(f"MAE : {mean_absolute_error(y_test,y_pred)}")
print(f"MSE : {mean_squared_error(y_test,y_pred)}")
print(f"r2_score : {r2_score(y_test,y_pred)}")

MAE : 7500.0
MSE : 62500000.0
r2_score : 0.375

In [73]:
print("Coefficient :", model.coef_)
print("Intercept :", model.intercept_)

Coefficient : [1250.]
Intercept : 37500.0

In [2]:
#ridge regression

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
X = np.array([
    [1, 20],
    [2, 22],
    [3, 25],
    [4, 28],
    [5, 30],
    [6, 35],
    [7, 38],
    [8, 40],
    [9, 42],
    [10, 45]
])

y = np.array([
    25000,
    30000,
    35000,
    42000,
    48000,
    55000,
    62000,
    70000,
    78000,
    85000
])

In [7]:
from sklearn.linear_model import Ridge

In [22]:
model = Ridge(alpha = 100)

In [23]:
model.fit(X,y);

In [24]:
pred = model.predict([[11,49]])

In [25]:
print("prediciton : ",pred[0])

prediciton :  87005.3945939768

In [26]:
from sklearn.linear_model import LinearRegression

In [27]:
model = LinearRegression()

In [28]:
model.fit(X,y);

In [29]:
lr_pred = model.predict([[11,49]])

In [30]:
print("prediction :",lr_pred[0])

prediction : 90093.67088607594

In [33]:
ofn = lr_pred[0] - pred[0]             #differnce

In [34]:
print(ofn)

3088.276292099137

In [65]:
#practice one hot encoding

In [66]:
import pandas as pd

In [67]:
df = pd.DataFrame({
    "City": ["Chennai","Madurai","Coimbatore","Chennai","Madurai"]
})

In [71]:
encode = pd.get_dummies(df,columns = ["City"],dtype = int)
encode

   City_Chennai  City_Coimbatore  City_Madurai
0             1                0             0
1             0                0             1
2             0                1             0
3             1                0             0
4             0                0             1

In [69]:
df_encode = pd.get_dummies("City",dtype = int)

In [70]:
df_encode

   City
0     1